[project]
name = "uv-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-core>=0.3.59",
    "langchain-groq>=0.3.2",
    "mcp-use>=1.2.10",
    "pandas>=2.2.3",
]
